# Generated by Django 2.2 on 2020-07-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempDir',
            fields=[
                ('pk_dir', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.FilePathField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
