# Generated by Django 2.2 on 2020-07-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdir',
            name='pk_dir',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
